#define LEFT_MOTOR_STEP_PIN 3
#define LEFT_MOTOR_DIR_PIN 6
#define RIGHT_MOTOR_STEP_PIN 2
#define RIGHT_MOTOR_DIR_PIN 5

#define STEPPER_ENABLE_PIN 8
#define LIMIT_SWITCH_X_PIN 9
#define LIMIT_SWITCH_Y_PIN 10

#define TILE_MATRIX_COL_SELECT_A_PIN 4
#define TILE_MATRIX_COL_SELECT_B_PIN 7
#define TILE_MATRIX_COL_SELECT_C_PIN 12
#define TILE_MATRIX_COL_SELECT_ENABLE_PIN 13
#define TILE_MATRIX_ROW_SELECT_A_PIN A0
#define TILE_MATRIX_ROW_SELECT_B_PIN A1
#define TILE_MATRIX_ROW_SELECT_C_PIN A2
#define TILE_MATRIX_DATA_PIN A3

#define MAGNET_SERVO_PIN 11