#define LEFT_MOTOR_STEP_PIN 3
#define LEFT_MOTOR_DIR_PIN 6
#define RIGHT_MOTOR_STEP_PIN 2
#define RIGHT_MOTOR_DIR_PIN 5

#define STEPPER_ENABLE_PIN 8
#define LIMIT_SWITCH_X_PIN 9
#define LIMIT_SWITCH_Y_PIN 10

#define MAGNET_SERVO_PIN -1